/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    'quickstart',
    'versioning',
    'orbitfile',
    {
      type: 'category',
      label: 'CLI',
      items: [
        'cli/index',
        {
          type: 'autogenerated',
          dirName: 'cli/commands',
        },
      ],
    },
  ],
};

module.exports = sidebars;
